# Generated by Django 4.0.5 on 2022-06-29 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('space_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'featured_names',
            },
        ),
        migrations.CreateModel(
            name='FeaturedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featured.featuredname')),
                ('product_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.originproduct')),
            ],
            options={
                'db_table': 'featured_products',
            },
        ),
    ]
