# Generated by Django 4.0.5 on 2022-06-30 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'featureds',
            },
        ),
        migrations.CreateModel(
            name='FeaturedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_products', to='featured.featured')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_products', to='products.productgroup')),
            ],
            options={
                'db_table': 'featured_products',
            },
        ),
    ]
