# Generated by Django 4.0.5 on 2022-06-24 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='FeaturedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featured.featured')),
                ('product_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.originproduct')),
            ],
            options={
                'db_table': 'featured_products',
            },
        ),
    ]
