# Generated by Django 4.0.5 on 2022-06-27 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'product_options',
            },
        ),
        migrations.RemoveField(
            model_name='cart',
            name='discount_product',
        ),
        migrations.AddField(
            model_name='originproduct',
            name='rate_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='originproduct',
            name='review_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='originproduct',
            name='sold_count',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
