# Generated by Django 4.0.5 on 2022-06-23 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='featuredproducts',
            old_name='featured_id',
            new_name='featured',
        ),
        migrations.RenameField(
            model_name='featuredproducts',
            old_name='product_code_id',
            new_name='product_code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category_id',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='main_category_id',
            new_name='main_category',
        ),
        migrations.AlterModelTable(
            name='featuredproducts',
            table='featured_products',
        ),
        migrations.AlterModelTable(
            name='maincategory',
            table='main_categories',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='sub_categories',
        ),
    ]
