# Generated by Django 4.0.5 on 2022-06-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_discount_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originproduct',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='originproduct',
            name='updated_at',
        ),
    ]
